### ISSUE TITLE
The purpose of this pull request is to accomplish the following tasks:

### ISSUE THREAD

**Issue by kebotbmfl** [kebotbmfl/kebotbmfl#10]
The purpose of this pull request is to accomplish the following tasks:

### Task List
- [ ] Create multiple test harness commands to optimize build minutes and display only necessary information.  I.E. don't need to print debug statements on successful builds.
- [ ] Create a gated build system where the next build step is only reached if the last one is successful
- [ ] Gated build system should only run each step once - the only exception is the `ng build` command which also gets run during testing
- [ ] Add a linter for HTML and CSS
- [ ] Add a git-hook system where certain checks happen before the commit.  Check out [Huskey]()
- [ ] Code reuse in circleci.  Please reference my fork of [c8](https://github.com/mcknasty/c8/blob/dba1d1ef77efdd98e96e4eb20c8c214a034a39b4/.circleci/config.yml)
- [ ] Create multiple spec files for error handling.  One file per class.  Give them a file extension of '`*.error-spec.ts`' have '`tsconfig.spec.json`' include in the test harness. 

### Github Task List
Supporting github workflows for the follow: 

- [ ] Angular version updates
- [ ] Auto merge dependabot package updates to pkg-updates branches.  **in progress**
- [ ] Auto merge security package updates to pkg-updates branch.
- [ ] Auto merge NG version updates to pkg-update branch.  Currently, there is a bug where a branch is getting pushed to once an hour. 
- [ ] GH pages has a [warning](https://app.circleci.com/pipelines/github/mcknasty/twitter-angular-clone.github.io/1693/workflows/2bc05397-dad7-4666-880e-cf6848281a78/jobs/6845?invite=true#step-107-1397_111) about an invalid URL.  Investigate!

_Originally posted by @mcknasty in https://github.com/mcknasty/twitter-angular-clone.github.io/pull/701_
